language: python

matrix:
  include:
    - python: 3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -y pymongo
  - conda install -y pandas
  - conda install -y xlrd
  - conda install -y gitpython
  - conda install -y unidecode
script:
  - py.test
